SNS_App/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

urlpatterns = [
    path('',SignupView.as_view(),name='signup'),
    path('login/',login_func,name='login'),
    path('logout/',logout_func,name='logout'),
    path('AuthenticateForEmailChange/',authenticate_for_email_change,name='AuthenticateForEmailChange'),
    path('EmailChange/<str:token>/',email_change,name='EmailChange'),
    path('EmailChange/<str:token>/Done/',email_change_done,name='EmailChangeDone'),
    path('PasswordChange/',password_change,name='PasswordChange'),
    path('PasswordChange/Done/',passeword_change_done,name='PasswordChangeDone'),
    path('PasswordReset/',password_reset,name='PasswordReset'),
    path('PasswordReset/Done/',password_reset_done,name='PasswordResetDone'),
    path('PasswordResetConfirm/<str:uidb64>/<str:token>/',password_reset_confirm,name='PasswordResetConfirm'),
    path('PasswordResetComplete/',password_reset_complete,name='PasswordResetComplete'),
    path('home/',HomeView.as_view(),name='home'),
    path('home2/',Home2View.as_view(),name='home2'),
    path('tweetCreate/<str:ISBNcode>',tweet_create,name='tweetCreate'),
    path('SelectItem/<str:ISBNcode>',select_item,name='SelectItem'), 
    path('TweetDelete/<int:tweet_pk>',tweet_del,name='TweetDelete'),
    path('CommentDelete/<int:comment_pk>',comment_del,name='CommentDelete'),
    path('profile_edit/<int:pk>',profile_editView.as_view(),name='profile_edit'),
    path('search_user/',SearchUserView.as_view(),name='search_user'),
    path('follower/<int:user_id>/',follower_show,name='follower'),
    path('following/<int:user_id>/',following_show,name='following'),
    path('tweet_like/',tweet_like_func, name='tweet_like'),
    path('comment_like/',comment_like_func, name='comment_like'),
    path('userPage/<int:pk>',userPageView.as_view(), name='userPage'),
    path('follow/',follow_func, name='follow'),
    path('CreateComment/<int:tweet_pk>',create_comment, name='CreateComment'),
    path('Chat/<int:user_id>', Chat.as_view(), name='Chat'),
    path('chat_room/<uuid:room_id>', chat_room, name='chat_room'),
    path('room/<int:pk>', room, name='room'),
    path('SearchItem/<str:From>',SearchItem.as_view(),name='SearchItem'),
    path('TweetOfItem/<str:ISBNcode>',TweetOfItemView.as_view(),name='TweetOfItem'),
]

SNS_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('SNS_App.urls')),
] +static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)\
  +static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

SNS_App/models.py
from django.contrib.auth.models import AbstractUser,UserManager
from django.db import models
from django.core.files.base import ContentFile
from sorl.thumbnail import get_thumbnail, delete
from django.utils import timezone
import uuid
from SNS_project import settings

class CustomUserManager(UserManager):
    use_in_migrations = True
 
    def _create_user(self,email, username, password, **extra_fields):
        
        if not email:
            raise ValueError('email must be set')

        if not username:
            raise ValueError('username must be set')

        if not password:
            raise ValueError('password must be set')

        email = self.normalize_email(email)
        user = self.model(email=email, username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
 
        return user
 
    def create_user(self, email, username, password, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, username, password, **extra_fields)

    def create_superuser(self, email=None, username=None ,password=None, **extra_fields):
 
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
 
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
 
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
 
        return self._create_user(email, username, password, **extra_fields)


class CustomUser(AbstractUser):

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    email = models.EmailField(unique=True)
    username = models.CharField(max_length=10, blank=False)
    profile=models.TextField(max_length=150,blank=True,null=True)
    ProfileImage=models.ImageField(upload_to='',default=settings.Default_image)

    class Meta(AbstractUser.Meta):
        swappable = 'AUTH_USER_MODEL'

class BookData(models.Model):
    ISBNcode=models.CharField(primary_key=True,max_length=30)
    title=models.CharField(max_length=100)
    author=models.CharField(max_length=30)
    itemPrice=models.CharField(max_length=30)
    itemUrl=models.CharField(max_length=100)
    imageUrl=models.CharField(max_length=100)

class TweetModel(models.Model):
    created_at = models.DateTimeField(default=timezone.now,blank=True)
    content=models.TextField()
    user=models.ForeignKey(CustomUser,verbose_name='紐づくユーザー',on_delete=models.CASCADE,blank=True)
    rating=models.IntegerField()
    book=models.ForeignKey(BookData,verbose_name='紐づく本',on_delete=models.CASCADE,blank=True)

    def __str__(self):
        return self.content[:10]


class Comment(models.Model):
    user=models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    text=models.TextField(max_length=150)
    tweet=models.ForeignKey(TweetModel,verbose_name='紐づくツイート',on_delete=models.CASCADE)

class Like(models.Model):
    tweet=models.ForeignKey(TweetModel,on_delete=models.CASCADE,null=True)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    comment=models.ForeignKey(Comment, on_delete=models.CASCADE,null=True)

class Connection(models.Model):
    following = models.ForeignKey(CustomUser, related_name='following', on_delete=models.CASCADE,null=True)
    followed = models.ForeignKey(CustomUser, related_name='followed', on_delete=models.CASCADE,null=True)

class Room(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    created_at = models.DateTimeField(default=timezone.now)
    room_member = models.ManyToManyField(
        'CustomUser',
        through='Entries',
        )

class Entries(models.Model):
    room = models.ForeignKey('Room', on_delete=models.CASCADE)
    user = models.ForeignKey('CustomUser', on_delete=models.CASCADE)
    joined_at=models.DateTimeField(default=timezone.now)

class Message(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    user=models.ForeignKey(CustomUser, on_delete=models.CASCADE,null=True)
    room = models.ForeignKey(Room,blank=True,null=True,on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)
    

SNS_App/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from django.core.exceptions import ValidationError
from .models import TweetModel,Comment
import re
from django.contrib.auth.forms import PasswordChangeForm,PasswordResetForm,SetPasswordForm
from django.template import loader

def isalnum(password):
    password_reg=re.compile('\A(?=.*?[a-z])(?=.*?[A-Z])(?=.*?\d)[a-zA-Z\d]{8,100}\Z')
    return password_reg.match(password) is not None

class CustomUserCreationForm(forms.ModelForm):

    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class' : 'form-control','placeholder': 'パスワード'}))
    password2 = forms.CharField(label='Repeat Password', widget=forms.PasswordInput(attrs={'class' : 'form-control','placeholder': 'パスワード(再入力)'}))

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update({'class' : 'form-control','placeholder': 'メールアドレス'})
        self.fields['username'].widget.attrs.update({'class' : 'form-control','placeholder': 'ユーザー名'})

    def clean_password1(self):
        password1 = self.cleaned_data.get("password1")
        if isalnum(password1):
            return password1
        else:
            raise forms.ValidationError('※半角英小文字大文字数字をそれぞれ1種類以上含む8文字以上100文字以下の\nパスワードを設定して下さい')

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('※1回目とパスワードが異なります')
        else:
            return password2

    def save(self, commit=True):
        user = super(forms.ModelForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user   


    class Meta:
        model = get_user_model()
        fields = ('email','username')

class EmailChangeForm(forms.ModelForm):

    def __init__(self, user, *args, **kwargs):
        super(EmailChangeForm, self).__init__(*args, **kwargs)
        self.user=user
        self.fields['email'].widget.attrs.update({'class' : 'form-control'})
    
    def save(self, commit=True):
        user=self.user
        print(user)
        user.email = self.cleaned_data["email"]
        print(user)
        if commit:
            user.save()
        return user   

    class Meta:
        model = get_user_model()
        fields = ('email',)

        labels = {
            'email':"新しいメールアドレス",
        }

class MyPasswordChangeForm(PasswordChangeForm):

    error_messages={
        'password_incorrect':'※元のパスワードが間違っています。もう一度入力してください。'
    }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['old_password'].widget.attrs.update({'class' : 'form-control','autofocus' : 'autofocus'})
        self.fields['new_password1'].widget.attrs.update({'class' : 'form-control'})
        self.fields['new_password2'].widget.attrs.update({'class':'form-control'})

    def clean_new_password1(self):
        new_password1=self.cleaned_data.get('new_password1')
        if isalnum(new_password1):
            return new_password1
        else:
            raise forms.ValidationError('※半角英小文字大文字数字をそれぞれ1種類以上含む8文字以上100文字以下の\nパスワードを設定して下さい')

    def clean_new_password2(self):
        new_password1 = self.cleaned_data.get("new_password1")
        new_password2 = self.cleaned_data.get("new_password2")
        if new_password1 and new_password2 and new_password1 != new_password2:
            raise forms.ValidationError('※1回目とパスワードが異なります')
        else:
            return new_password2

class MyPasswordResetForm(PasswordResetForm):
    email=forms.EmailField(widget=forms.EmailInput(attrs={'class' : 'form-control','placeholder': 'メールアドレス'}))

    def clean_email(self):
        email=self.cleaned_data.get('email')
        users=self.get_users(email)
        user=None
        for user_ in users:
            user=user_
        if not user:
            raise forms.ValidationError('有効なメールアドレスを入力してください。')
        else:
            return email
    

class MySetPasswordForm(SetPasswordForm):
   
    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(SetPasswordForm, self).__init__(*args, **kwargs)
        self.fields['new_password1'].widget.attrs.update({'class' : 'form-control'})
        self.fields['new_password2'].widget.attrs.update({'class':'form-control'})

    def clean_new_password1(self):
        new_password1=self.cleaned_data.get('new_password1')
        if isalnum(new_password1):
            return new_password1
        else:
            raise forms.ValidationError('※半角英小文字大文字数字をそれぞれ1種類以上含む8文字以上100文字以下の\nパスワードを設定して下さい')

    def clean_new_password2(self):
        new_password1 = self.cleaned_data.get("new_password1")
        new_password2 = self.cleaned_data.get("new_password2")
        if new_password1 and new_password2 and new_password1 != new_password2:
            raise forms.ValidationError('※1回目とパスワードが異なります')
        else:
            return new_password2

class TweetCreationForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(TweetCreationForm, self).__init__(*args, **kwargs)
        self.fields['content'].widget.attrs.update({'class' : 'form-control','placeholder':'感想を書こう!','autofocus' : 'autofocus'})
        self.fields['rating'].widget.attrs.update({'class':'d-transparent'})
        
    
    class Meta:
        model = TweetModel
        fields = '__all__'

        labels = {
                  'content':"本文",
                  'snsImage':"画像",
        }

        error_messages = {
            "content": {
                "required": "本文が入力されていません",
            },
            "rating": {
                "required": "評価を選んで下さい",
            },
        }

        

class CustomUserChangeForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
            super(CustomUserChangeForm, self).__init__(*args, **kwargs)
            self.fields['username'].widget.attrs.update({'class' : 'form-control'})

    ProfileImage= forms.ImageField(widget=forms.widgets.FileInput)

    class Meta:
        model = get_user_model()
        fields = ('username','ProfileImage')

class CreateCommentForm(forms.ModelForm):

    def __init__(self,*args,**kwargs):
        super(CreateCommentForm, self).__init__(*args, **kwargs)
        self.fields['text'].widget.attrs.update({'class' : 'form-control','placeholder':'コメントを書く','id':'comment_input'})

    class Meta:
        model = Comment
        fields = ('text',)
    
class RakutenSearchForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(RakutenSearchForm, self).__init__(*args, **kwargs)
        self.fields['page_number'].initial = 1
        self.fields['category'].widget.attrs.update({'class' : 'form-select'})

    BOOK_CHOICES = (
        ('001', '本全般'),
        ('001004001', 'ミステリー・サスペンス'),
        ('001004002', 'SF・ホラー'),
        ('001004003', 'エッセイ'),
        ('001004004', 'ノンフィクション'),
        ('001004008', '日本の小説'),
        ('001004009', '外国の小説'),
        ('001004016', 'ロマンス'),
        ('001017', 'ライトノベル'),
    )

    category = forms.fields.ChoiceField(
        choices=BOOK_CHOICES,
        required=False,
        label='ジャンル',
    )
    title=forms.CharField(label='タイトル',max_length=200,required=False)
    page_number=forms.IntegerField(widget=forms.HiddenInput)

templates/Itemlist.html
{% extends 'base.html' %}
{% load widget_tweaks%}
{% load static %}

{% block head %}
<link href="{% static 'Itemlist.css' %}" rel="stylesheet"> 
{% endblock head %}
{% block content %}
<div class="text-center my-5">
    <form method="post" action="{% url 'SearchItem' From %}" class="d-flex" id="Search-form">{% csrf_token %}
        <div class="align-items-center w-100">
            {% render_field form.title class="form-control" placeholder="キーワードから探す"%}
        </div>
        {{ form.category}}
        {{ form.page }}
        <button class="btn btn-success" type="submit">検索</button>
    </form>
</div>
<div class="container my-5">
    <div class="mb-5 border-bottom">
        {% if keyword %}
        <h3>「{{ keyword }}」の検索結果</h3>
        {% endif %}
    </div>
    <div class="bookList">
        {% for book in book_data %}
            <div class="bookTag">
                    <img src="{{ book.image }}" alt="" class="book-img me-3">
                    <div class="px-2 py-3">
                        <h5><a href="{{ book.itemUrl }}" class="book-title">{{book.title}}</a></h5>
                        <p class="text-primary">{{book.author}}</p>
                        <h3 class="text-warning">{{book.itemPrice}}円<sub class="text-secondary">(税込み)</sub></h3>
                    </div>
                    {% if From == "Select" %}
                     <div class="ms-auto"><a href="{% url 'SelectedItem' book.ISBNcode %}" class="btn btn-success" role="button" aria-pressed="true">選択</a></div>
                    {% elif From == "Search" %}
                    <div class="ms-auto"><a href="{% url 'TweetOfItem' book.ISBNcode %}" class="btn btn-success" role="button" aria-pressed="true">みんなの投稿を見る</a></div>
                    {% endif %}
            </div>
        {% empty %}
                <p>該当するものはありません</p>
        {% endfor %}
    </div>
    <nav aria-label="Page navigation example">
        <ul class="pagination">
          {% if page != 1 %}
          <li class="page-item">
            <button class="page-link" id="page-link-left" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
            </button>
          </li>
          {% endif %}

          {% for num in for_range %}
            {% if page == num %}
                <li class="page-item active"><button class="page-link page-link-num">{{ num }}</button></li>
            {% else %}
                <li class="page-item"><button class="page-link page-link-num">{{ num }}</button></li>
            {% endif %}
          {% endfor %}

          {% if page != 10 %}
          <li class="page-item">
            <button class="page-link" id="page-link-right" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
            </button>
          </li>
          {% endif %}
        </ul>
      </nav>
</div>
{% endblock content %}

{% block footer %}
<script type="text/javascript">

var Input_page=document.getElementById("id_page");

var pagingButtons=document.getElementsByClassName("page-link-num");
for(const pagingButton of pagingButtons){
  pagingButton.addEventListener("click", function (event) {
    Input_page.value=this.innerHTML;
    let form = document.getElementById("Search-form");
    form.submit();
});
}

if(Input_page!=1){
  var backButton=document.getElementById("page-link-left");
  backButton.addEventListener("click",function (event){
    Input_page.value=Number(Input_page.value)-1;
    let form = document.getElementById("Search-form");
    form.submit();
});
}

if(Input_page!=10){
  var nextButton=document.getElementById("page-link-right");
  nextButton.addEventListener("click",function (event){
    Input_page.value=Number(Input_page.value)+1;
    let form = document.getElementById("Search-form");
    form.submit();
  });
}
</script>
{% endblock footer %}

templates/authenticate_for_email_change.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">

{% endblock head %}
{% block title %}
パスワード認証
{% endblock title %}


{% block content %}
  
<div class="text-center mt-5 d-flex">
 <main class="ms-auto me-auto">
    <form method="POST">{% csrf_token %}
      <h1 class="h3 mb-3 fw-normal">メールアドレスの変更にはパスワードの入力が必要です</h1>
      <p class="text-warning">{{error}}</p>
      <input type="password"  class="form-control" name="password" placeholder="パスワード" required>
      <div class="d-flex">
        <button class="btn btn-success mt-3 ms-auto" type="submit">次へ</button>
      </div>
    </form>
  </main>
</div>
{% endblock content %}

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link href="{% static 'home.css' %}" rel="stylesheet"> 
<link href="{% static 'up_button.css' %}" rel="stylesheet"> 
{% endblock head %}
{% block title %}
ホーム
{% endblock title %}

{% block header %}
<!-- navbar(検索フォーム付き) -->
<nav class="navbar bg-dark sticky-top mb-3">
  <div class="container-fluid">
    <a class="navbar-brand navbarTextColor"><i class="far fa-smile-beam smileIcon"></i>BOOK_SNS</a>

    <ul class="nav nav-pills">
      <li class="nav-item"><a href="{% url 'SearchItem' 'Search' %}" class="nav-link"><i class="fas fa-search"></i>本を探す</a></li>
      <li class="nav-item"><a href="{% url 'Chat' user.id %}" class="nav-link">チャット</a></li>
      <li class="nav-item"><a href="{% url 'userPage' user.id %}" class="nav-link">マイページ</a></li>
    </ul>

    <form method="GET" class="d-flex ms-auto Search-user" action="{% url 'search_user' %}">
      <input class="form-control" type="text" placeholder="ユーザーを検索" aria-label="Search" name="keyword_user">
      <button class="btn btn-success" type="submit"><i class="fas fa-search"></i><span>検索</span></button>
    </form>
  </div>

  <div class="container">
    <ul class="nav nav-pills mx-auto page-select">
      {% if selected_page == 'home' %}
      <li class="nav-item selected-page"><a href="{% url 'home' %}" class="nav-link">新着の投稿</a></li>
      <li class="nav-item"><a href="{% url 'home2' %}" class="nav-link">フォローした人の投稿</a></li>
      {% else %}
      <li class="nav-item"><a href="{% url 'home' %}" class="nav-link">新着の投稿</a></li>
      <li class="nav-item selected-page"><a href="{% url 'home2' %}" class="nav-link">フォローした人の投稿</a></li>
      {% endif %}
    </ul>
  </div>

</nav>
{% endblock header %}

{% block content %}
<!-- ログアウト、検索バー、tweetボタンなど -->
<div class="mx-3 mb-4">
    <form method="GET" class="d-flex">
      <a href="{% url 'logout' %}" class="btn btn-success" role="button" aria-pressed="true">ログアウト</a>
        <input type="text" class="form-control Search-form ms-auto" placeholder="tweetを検索" name="keyword">
        <button class="btn btn-outline-success" type="submit"><i class="fas fa-search"></i><span>検索</span></button>
    </form>
</div>

  <div class="font-bold profile-container d-flex flex-wrap align-items-center">
    <a href="{% url 'userPage' user.id %}" class="me-3" role="button" aria-pressed="true">
      <img src="{{ user.ProfileImage.url }}" class="user-icon" >
    </a>
    {{user.username}}
    <a href="{% url 'SearchItem' 'Select' %}" class="btn btn-success ms-3" role="button" aria-pressed="true">投稿する</a>
  </div>
<!------------------------------------->

<!-- 投稿の一覧 -->
<div id="tweet_list">
  {% for tweet in tweetmodel_list reversed %}
  <div class="tweet-container container border border-secondary" id="test">
      <p class="font-bold d-flex">
        <a href="{% url 'userPage' tweet.user.id %}" class="me-3" role="button" aria-pressed="true">
        <img src="{{ tweet.user.ProfileImage.url }}" class="user-icon">
        </a>
        {{ tweet.user.username }} 
      </p>
     <p class="tweet-text">{{ tweet.content | linebreaksbr }}</p>
     <div class="d-flex book-container border border-secondary">
        <img src="{{ tweet.book.imageUrl }}" alt="" class="book-img me-3">
        <div>
         <h6><a href="{{ tweet.book.itemUrl }}" class="book-title">{{ tweet.book.title}}</a></h6>
         <p class="text-primary">{{ tweet.book.author }}</p>
        </div>
     </div>
    <div class="d-flex"> 
      <div class="d-flex">
        {% if tweet.id in liked_list %}
            <button class="like" v-on:click="tweet_like_post" id="tweet_{{tweet.id}}" data-like-id="{{tweet.id}}"><i class="fas fa-lg fa-heart like-after"></i></button>
        {% else %}
            <button class="like" v-on:click="tweet_like_post" id="tweet_{{tweet.id}}" data-like-id="{{tweet.id}}"><i class="far fa-lg fa-heart like-before"></i></button>      
        {% endif %}
        <p id="tweet_count_{{tweet.id}}" class="count"> {{ tweet.like_set.count }} </p>
      </div>
      {% with ''|center:5 as range %}
       <div class="stars ms-auto">
        {% for _ in range %}
         {% if forloop.counter <= tweet.rating %}
          <span class="star-yellow">★</span>
         {% else %}
          <span class="star-gray">★</span>
         {% endif %}
        {% endfor %}
       </div>
      {% endwith %}
    </div>
    <hr>
     <div class="comment">
      <a href="{% url 'CreateComment' tweet.id %}" class="me-3" role="button" aria-pressed="true">
       コメント>
      </a>
     </div>
  </div>
  {% endfor %}
</div>
<!------------------------------>

<button id="UpButton"><i class="fas fa-angle-double-up"></i></button>
{% endblock content %}

{% block footer %}
<script src="{% static 'up_button.js' %}"></script>

<!--いいね機能のAjax処理-->
<script type="text/javascript">
const TweetListApp=Vue.createApp({
    data:()=>({
        like_url:"{% url 'tweet_like' %}"
    }),
    methods:{
        tweet_like_post:function(event){
          const headers={
              'X-Requested-With': 'XMLHttpRequest',
              'Content-Type':'application / json',
              'X-CSRFToken':'{{ csrf_token }}'
          }
          let like_data={
            "like_id":event.currentTarget.dataset.likeId,
          }
          like_data=JSON.stringify(like_data)
          axios.post(this.like_url,like_data,{headers:headers})
          .then(function(res){
            const target_button=document.getElementById('tweet_'+res.data.like_id);
            if(res.data.liked){
              target_button.innerHTML="<i class='fas fa-lg fa-heart like-after'></i>"
            }else{
              target_button.innerHTML="<i class='far fa-lg fa-heart like-before'></i>"
            }
            target_counter = document.getElementById("tweet_count_"+res.data.like_id);
            target_counter.innerText=res.data.count
          })
          .catch(function(error){
            console.log(error)
          })
        }
    }
})
TweetListApp.config.compilerOptions.delimiters = ['[[', ']]']
TweetListApp.mount('#tweet_list')
</script>
{% endblock footer%}

templates/profile_edit.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link href="{% static 'profile_edit.css' %}" rel="stylesheet"> 
{% endblock head %}

{% block title %}
プロフィール変更ページ
{% endblock title %}

{% block content %}
  
<div class="container text-center mt-5">
  <main class="form-edit">
     <i class="far fa-grin-squint edit-title"><span class="line-break">プロフィールを</span><span class="line-break">変更しよう！</span></i>
    <form method="POST" enctype="multipart/form-data">{% csrf_token %}
      <div class="mb-3">
        <img class="profile_image" src="{{user.ProfileImage.url}}" id="preview">
      </div>
      <div class="mb-3">
        <label for="id_ProfileImage" class="image-field-label">
            画像を選択{{form.ProfileImage}}
        </label>
      </div>

      <div class="form-floating mb-3">
        {{form.username}}
        <label for="id_username">ユーザー名</label>
      </div>
      <div class="d-flex">
       <button class="ms-auto btn btn-success" type="submit">変更</button>
      </div>
    </form>
    <div class="mt-5 d-flex">
      <a href="{% url 'AuthenticateForEmailChange' %}" class="btn btn-success me-auto" role="button">メールアドレス変更</a>
    </div>
    <div class="mt-4 d-flex">
      <a href="{% url 'PasswordChange' %}" class="btn btn-success me-auto" role="button">パスワード変更</a>
    </div>
  </main>
</div>
{% endblock content %}

{% block footer %}
<script src="{% static 'profile_edit.js' %}"></script>
{% endblock footer%}